---
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: myapp-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
  # - http:
  #     paths:
  #     - path: /v1
  #       backend:
  #         serviceName: myappv1-svc
  #         servicePort: 80
  #     - path: /v2
  #       backend:
  #         serviceName: myappv2-svc
  #         servicePort: 80
  - host: app1.157.230.192.235.nip.io
    http:
      paths:
      - backend:
          serviceName: myappv1-svc
          servicePort: 80
  - host: app2.157.230.192.235.nip.io
    http:
      paths:
      - backend:
          serviceName: myappv2-svc
          servicePort: 80
  backend:
    serviceName: myappv2-svc
    servicePort: 80

