---
apiVersion: v1
kind: Namespace

metadata:
  name: nwapp
  labels:
    version: v1

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwapp-config
  namespace: nwapp

data:
  db_password: changeit

---
apiVersion: v1
kind: Secret

metadata:
  name: nwapp-secret
  namespace: nwapp

data:
  db_password: Y2hhbmdlaXQ=


---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nwapp-deploy
  namespace: nwapp
  labels:
    name: nwapp-pod
    version: v1

spec:
  replicas: 3
  selector:
    matchLabels:
      name: nwapp-pod
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: nwapp-pod
      labels:
        name: nwapp-pod
        version: v1
    spec:
      containers:
      - name: nwapp
        image: stackupiss/northwind-app:v2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: nwapp-port
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DB_HOST
          value: "nw-svc"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nwapp-secret
              key: db_password
        ports:
        - name: nwapp-port
          containerPort: 3000

