# the only environment is DB_PASSWORD
# use ns nwdb

---
apiVersion: v1
kind: Namespace

metadata:
  name: nwapp
  labels:
    version: v1

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwapp-config
  namespace: nwapp

data:
  db_password: changeit

---
apiVersion: v1
kind: Secret

metadata:
  name: nwapp-secret
  namespace: nwapp

data:
  db_password: Y2hhbmdlaXQ=


---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nwdb-deploy
  namespace: nwapp
  labels:
    name: nwdb-pod
    version: v1

spec:
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      name: nwdb-pod
      version: v1
  template:
    metadata:
      name: nwdb-pod
      labels:
        name: nwdb-pod
        version: v1
    spec:
      containers:
      - name: nwdb-container
        image: stackupiss/northwind-db:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nwapp-secret
              key: db_password
            # configMapKeyRef:
            #   name: nwapp-config
            #   key: db_password
        ports:
        - containerPort: 3306