version: '3'

networks:
  appnet:


volumes:
  appvol:

services:
  mysql:
    image: guanyou/mysql:v1
    build:
      context: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
    networks:
      - appnet
    volumes:
      - appvol:/var/lib/mysql

  nwapp:
    image: guanyou/server:v2
    build:
      context: ./server
    environment:
      - DB_HOST=mysql
    ports:
      - 80-85:3000
    networks:
      - appnet